# Generated by Django 2.2.6 on 2019-11-04 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='perfil',
            field=models.ImageField(blank=True, upload_to='imagen_perfil'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='portada',
            field=models.ImageField(blank=True, upload_to='imagen_portada'),
        ),
    ]
